app:
  image: tutum/hello-world:latest
  ports:
   - "80"
  links:
   - redis
  env_file: .env

lb:
  build: ./
  links:
  - consul
  ports:
  - "80:80"

redis:
  image: redis

consul:
  command: -server -bootstrap -advertise 10.0.2.15
  image: progrium/consul:latest
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"

registrator:
  command: consul://consul:8500
  image: gliderlabs/registrator:latest
  links:
  - consul
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"
